# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzashop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
