# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzashop', '0006_auto_20171118_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='pizzashop.Customer', verbose_name='Клиент'),
        ),
    ]
