# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzashop', '0008_auto_20171118_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, max_length=300, verbose_name='Описание'),
        ),
    ]
