# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzashop', '0014_auto_20171205_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='price_per_item',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='total_price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
