# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-13 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzashop', '0018_auto_20171211_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='pizzashop/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CR', 'Создан'), ('NCF', 'Не подтвержден'), ('CF', 'Подтвержден'), ('CBC', 'Отменен заказчиком'), ('CBO', 'Отклонен оператором'), ('CM', 'Выполнен'), ('FL', 'Провален')], default='CR', max_length=3, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Готовность'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzashop.Item', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzashop.Order', verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_per_item',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Сумма заказа'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
    ]
